// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh66QuBNkIxvo8MItj8_5PsWSb9P2trsI',
    appId: '1:810123065806:web:8a4578fda8bb24d043139f',
    messagingSenderId: '810123065806',
    projectId: 'eventing-adeff',
    authDomain: 'eventing-adeff.firebaseapp.com',
    storageBucket: 'eventing-adeff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOvOHXU5TJSLvRrqFGRmlUbJGShoO19CY',
    appId: '1:810123065806:android:454df0e3730962d143139f',
    messagingSenderId: '810123065806',
    projectId: 'eventing-adeff',
    storageBucket: 'eventing-adeff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPYcdyYQ-TeagnYNL8LDqUzZ-s-Pd5uFc',
    appId: '1:810123065806:ios:d952fddca3dfb80443139f',
    messagingSenderId: '810123065806',
    projectId: 'eventing-adeff',
    storageBucket: 'eventing-adeff.appspot.com',
    iosClientId: '810123065806-k8r8p69ul14n6tfc15qb4lg8359p1ovj.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPYcdyYQ-TeagnYNL8LDqUzZ-s-Pd5uFc',
    appId: '1:810123065806:ios:d952fddca3dfb80443139f',
    messagingSenderId: '810123065806',
    projectId: 'eventing-adeff',
    storageBucket: 'eventing-adeff.appspot.com',
    iosClientId: '810123065806-k8r8p69ul14n6tfc15qb4lg8359p1ovj.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventingApp',
  );
}
